### ISSUE TITLE
ICSP incorrect metadata for non-catalog images

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#172]
# Version
alpha3

# What happened?

Non-catalog image icsp's are populated with `operators.openshift.org/catalog: "true"`

example:
```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: ubi-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - localhost:5002/ubi8/ubi
    source: registry.redhat.io/ubi8/ubi
```

# What you expected to happen?

I expect the label value to be "false"

# How to reproduce it (as minimally and precisely as possible)?

Publish non-catalog images results in incorrect ICSP label
