### ISSUE TITLE
Metadata not found

### ISSUE THREAD

**Issue by SDBrett** [openshift/oc-mirror#178]
# What happened?

The  command `./bin/oc-mirror list updates --config imageset-config.yaml --dir test-create --log-level debug`  returns

```
DEBUG looking for metadata file at "publish/.metadata.json"
error: no metadata detected
```

-
# What you expected to happen?

List updates

# How to reproduce it (as minimally and precisely as possible)?

I'm running through the usage steps on the README.md document. 
- Ran `make build`
- Created an image set from the reference file
- Run example command `./bin/oc-mirror list updates --config imageset-config.yaml --dir test-create --log-level debug` 

# Anything else we need to know?

imageset-config.yaml

``` yaml
apiVersion: tmp-redhatgov.com/v1alpha1
kind: ImageSetConfiguration
mirror:
  ocp:
    channels:
      - name: stable-4.8
      - name: fast-4.8
      - name: stable-4.9
    graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8
      headsOnly: true
      packages:
        - name: couchbase-operator
          versions:
            - '1.4.0'
        - name: crunchy-postgresql-operator
          channels:
            - name: 'stable'
  additionalimages:
    - name: registry.redhat.io/ubi8/ubi:latest
  blockedimages:
    - name: alpine
    - name: redis 
```

**Comment by afflom** [comment]
First off, thank you for trying out oc-mirror.

If there is no metadata available, we would want to dump the output of a dryrun from all of the mirroring functions within the app. The word "update" makes less sense in this context. Perhaps we should just change this to dryrun. Wdyt @jpower432 ?


Unrelated, I have a trimmed down config that might make your evaluation a bit easier. It needs to eventually make it into the repo, but I'll post it here later.

**Comment by afflom** [comment]
This config might be helpful. It has an example registry backend and demos all of the major sections.  Also, when downloading operator catalogs consider using  `--continue-on-error` and/or `--skip-missing`, due to some images being intermittently unavailable. 

```
apiVersion: tmp-redhatgov.com/v1alpha1
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: localhost:5010/demo/metadata
    skipTLS: true
mirror:
  ocp:
    channels:
      - name: stable-4.9
    graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.9
      headsonly: true
  additionalimages:
    - name: registry.redhat.io/ubi8/ubi:latest
    - name: quay.io/podman/stable:latest
  helm:
    repos: 
      - name: podinfo
        url: https://stefanprodan.github.io/podinfo
        charts: 
          - name: podinfo
            version: 5.0.0
```
