### ISSUE TITLE
oc-mirror produces catalog artifacts with empty channels when imageset config filters operator to specific version

### ISSUE THREAD

**Issue by bkkhoo** [openshift/oc-mirror#210]
# Version

```console
$ oc-mirror version
v0.1.0-alpha.3
```

# What happened?
Executing `oc-mirror --config imageset-config.yaml file://output-dir` with the following config to mirror to directory:
```
apiVersion: tmp-redhatgov.com/v1alpha1
kind: ImageSetConfiguration
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.9
      headsOnly: false
      packages:
        - name: rhacs-operator
          channels:
          - name: latest
          versions:
          - '3.67.0'
```

The command completed successfully, but some of the channels have empty entris:
```
{
    "schema": "olm.channel",
    "name": "rhacs-3.66",
    "package": "rhacs-operator",
    "entries": []
}
```

`opm validate` of the catalog show this:
```
$ opm validate output-dir/oc-mirror-workspace/src/catalogs
FATA[0000] invalid index:
└── invalid package "rhacs-operator":
    ├── invalid channel "rhacs-3.62":
    │   └── channel must contain at least one bundle
    ├── invalid channel "rhacs-3.64":
    │   └── channel must contain at least one bundle
    ├── invalid channel "rhacs-3.65":
    │   └── channel must contain at least one bundle
    └── invalid channel "rhacs-3.66":
        └── channel must contain at least one bundle
```

# What you expected to happen?
Empty channels should be removed, catalog image with empty channels will not run.
