### ISSUE TITLE
Feature request - Add skip-deps field to not include dependencies

### ISSUE THREAD

**Issue by nschambu** [openshift/oc-mirror#221]
I apologize if this isn't the place to open feature requests. Let me know if there is a better place.

# Feature request

The [Diff struct](https://github.com/operator-framework/operator-registry/blob/master/alpha/action/diff.go#L190) used by oc-mirror includes a SkipDependencies boolean which allows the curated catalog to not pull in the dependencies of the specified package. We have an edge use case that could like to take advantage of this option to be able to create an ImageSetConfiguration object with the exact versions of each dependency in the stack to ensure the same curated catalog is created whether it's run today, tomorrow, or next week.

I would expect that to align with the Diff struct, this property would be global for each catalog in an ImageSetConfiguration. For example, you can't specify that you don't want the dependency resolution for one package in a catalog while saying that you want it for others. It's an all or nothing situation.

Example usage:

```yaml
apiVersion: tmp-redhatgov.com/v1alpha1
kind: ImageSetConfiguration
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8
      skipdeps: true
      packages:
        - name: elasticsearch-operator
          versions: 
            - '5.2.3-31'
```

Again, let me know if this is the wrong place to be requesting this or if you need more information.
