### ISSUE TITLE
Failed to decode the helm config 

### ISSUE THREAD

**Issue by zhouying7780** [openshift/oc-mirror#228]
# Version

```console
$ oc-mirror version
v0.1.0-alpha.3
```

# What happened?
Failed to decode the helm config:
[root@localhost oc-helm]# cat imageset.yaml 
apiVersion: tmp-redhatgov.com/v1alpha1
kind: ImageSetConfiguration
mirror:
  helm:
    repos: 
      - name: podinfo
        url: https://stefanprodan.github.io/podinfo
        charts: 
          - name: podinfo
            version: 5.0.0
    local:
      charts: 
        - name: podinfo-local
          path: /home/ocmirrortest/oc-helm/podinfo-6.0.0.tgz
[root@localhost oc-helm]# oc-mirror --config imageset.yaml file://out
error: decode tmp-redhatgov.com/v1alpha1, Kind=ImageSetConfiguration: json: cannot unmarshal object into Go struct field Helm.mirror.helm.local of type []v1alpha1.Chart

Enter text here.
Attach the relevant portions of your `.openshift_bundle.log`.

# What you expected to happen?
No failed.
Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

Enter text here.

**Comment by jpower432** [comment]
:wave: @zhouying7780. Thanks for finding this error in our example docs. I have update the helm example config on the linked PR. Please see below for an example of the corrected config.
```
apiVersion: tmp-redhatgov.com/v1alpha1
kind: ImageSetConfiguration
mirror:
  helm:
    repos:
      - name: podinfo
        url: https://stefanprodan.github.io/podinfo
        charts:
          - name: podinfo
            version: 5.0.0
    local:
      - name: podinfo-local
        path: /home/ocmirrortest/oc-helm/podinfo-6.0.0.tgz
```
