### ISSUE TITLE
Error info is ambiguous when versions is wrong in the ImageSetConfiguration

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#240]
Description of problem:
Error info is ambiguous when versions is wrong in the ImageSetConfiguration

Version-Release number of selected component (if applicable):

How reproducible:

Steps to Reproduce:
1. Use the imagesetconfig as follow :
`oc-mirror --config imageset.yaml file://testin --dry-run`
```
apiVersion: tmp-redhatgov.com/v1alpha1
kind: ImageSetConfiguration
mirror:
  ocp:
    channels:
      - name: stable-4.9
        versions:
          - 4.9
    graph: true
```

Actual result:
1. The error info is ambiguous when versions is wrong in the ImageSetConfiguration
[root@localhost 1206]# oc-mirror --config imageset.yaml file://testin --dry-run
error: decode tmp-redhatgov.com/v1alpha1, Kind=ImageSetConfiguration: json: cannot unmarshal number into Go struct field ReleaseChannel.mirror.ocp.channels.versions of type string

Expect result:
1. Show clear info to help user to correct the configure and at the some time oc-mirror should be able to parse either 4.9.0 or 4.9 since the cli accepts either way

https://bugzilla.redhat.com/show_bug.cgi?id=2029367
