### ISSUE TITLE
Registry backends not validated

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#249]
# What happened?
The following storageConfig does not cause the application to `exit 1`. 
```
storageConfig:
  registry:
    imageURL: example.com/example/oc-mirror
    skipTLS: false
```

# What you expected to happen?

Since this imageURL is not an accessible v2 registry, it should cause oc-mirror to exit with an error.
