### ISSUE TITLE
QUAY push has issues with the operator-index

### ISSUE THREAD

**Issue by bit4man** [openshift/oc-mirror#253]
As requested on chat, I'm filing a detailed report here with full dumps.  The non public hosts mentioned in the dump are not accessible publicly. 

# Version

```console
$ oc-mirror version
v0.1.0-alpha.3
```

# What happened?
[bzissue-data.log.gz](https://github.com/openshift/oc-mirror/files/7810463/bzissue-data.log.gz)
Error while "processing redhat-operator-index/v4.9" - MANIFEST_UNKNOWN. Details in the attached logfile.

# What you expected to happen?

Successful mirror to local QUAY repository. 

# How to reproduce it (as minimally and precisely as possible)?

Pull latest version of oc-mirror, build it and run with the following basic config:

```yaml
apiVersion: tmp-redhatgov.com/v1alpha1
kind: ImageSetConfiguration
mirror:
   ocp:
    channels:
      - name: stable-4.9
     graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.9
      headsOnly: false
      packages:
        - name: advanced-cluster-management
          startingVersion: '2.4.0'
  helm:
    repos:
      - name: podinfo
        url: https://stefanprodan.github.io/podinfo
        charts:
          - name: podinfo
            version: '5.0.0'
  additionalimages:
    - name: registry.redhat.io/ubi8/ubi:latest
```
I presume that the helm and additionaimages can be excluded and the error will still happen. 

```console
$ oc-mirror --log-level=debug --config=../example-config.yaml file://mirror
```
See logfile for details.
