### ISSUE TITLE
Red Hat Quay registry with multiple resolvable A records fails to push blobs when a hostname for the registry is supplied that differs from `SERVER_HOSTNAME` set in the Quay configuration

### ISSUE THREAD

**Issue by jharmison-redhat** [openshift/oc-mirror#279]
# Version

3660f79441d753560f33549a725d0339186649e0

# What happened?

`error: error writing metadata: PATCH https://registry.disco.redhat4govaws.io/v2/oc-mirror/imageset-metadata/blobs/uploads/870bca0b-6a34-4482-a08d-159163fc85ca: UNAUTHORIZED: access to the requested resource is not authorized; map[]`

# What you expected to happen?

imageset-metadata to publish at the specified registry endpoint

# How to reproduce it (as minimally and precisely as possible)?

Registry is a Quay server, with `SERVER_HOSTNAME` set to registry.disco.redhat4govaws.io which is a publicly accessible DNS record that resolves to the EIP attached to the instance.

```yaml
apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: registry.internal.disco.redhat4govaws.io/oc-mirror/imageset-metadata:latest
mirror:
  ocp:
    channels:
      - name: stable-4.9
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.9
      headsOnly: false
      packages:
        - name: compliance-operator
          startingVersion: '0.1.44'
  additionalimages:
    - name: registry.redhat.io/ubi8/ubi:latest
```

ImageSetConfiguration references a private hosted zone record for `registry.internal.disco.redhat4govaws.io` which resolves to the internal VPC IP address of the same instance.

```console
$ ./bin/oc-mirror --config ~/imageset-config.yml --dir=~/mirror-content docker://registry.internal.disco.redhat4govaws.io/oc-mirror
```

# Anything else we need to know?

I believe Quay, being aware of its hostname and only aware of one of the names that resolve to that instance, is returning what it believes to be the correct `SERVER_HOSTNAME` when returning a path in which to store blobs, and not respecting the `Hostname` on HTTP requests made to the internal DNS record.

We should either:
- Report upstream and ask them to return HTTP paths without hostnames
- Add a shim that checks if the HTTP Hostname for a request fails to match Quay - though actually, thinking about it, this might be a problem in the event that a registry is simply passing off an S3 blob address for example. Hmm. I'm not sure of the right thing to do here. It would be a messy shim.
