### ISSUE TITLE
[RFE] Creating mirroring config from running clusters

### ISSUE THREAD

**Issue by dmesser** [openshift/oc-mirror#304]
# What is desired

The configuration file for `oc mirror` needs to be assembled by the user. Some users may have running clusters that they simply want to clone. `oc mirror` should have a feature that allows to create mirroring configuration that corresponds to a cluster that it is being pointed at.

# What you expected to happen?

`oc mirror` would make use of the `oc` context that it is running in as a plugin to connect to cluster. It would need sufficient permissions to introspect the cluster and survey the following data points:

* cluster version running
* installed CatalogSources / operator catalogs
* installed operators, including their versions and channels
* bonus points: determining installed helm releases and their source charts

The output of the survey should be a ready-to-run mirror configuration file that is stored on disk or sent to stdout for reuse.

**Comment by afflom** [comment]
I have some thoughts and questions about this:

This would be very helpful for users transitioning from lab environments to subsequent iterations of their practiced cluster deployments. There is a lot to be said for easing the process of authoring the imageset config. We had originally pushed back on this request in favor of an ansible role or script to retrieve this information, but this might be a good fit for oc-mirror. 

@dinhxuanvu If an operator name and its version are dumped from a cluster, is there any correlation within the cluster to determine the catalog that the operator was installed from? How does the operator hub configuration play into this? Or will we have to get the name and version and then use the oc-mirror list workflows to discover this information?

@dmesser  I do not see time in the schedule to implement this feature in 4.11. What release are you targeting?

**Comment by joehuizenga** [comment]
I have hacked up a simple PoC in goLang that kinda does this, if there is interest, I can look into how to share it, right now its inside an ibm git repo

## logic

- get all catalogsources running in cluster
  - run them and use grpc to get heads of channel from each catalog
  - build cache catalog:pkg:channel -> bundle version

- get all the operators installed in the cluster and loop thru them
  - get the subscription that installed the operator
    - get the information from subscription and add/merge an entry to the ISC

- get all operandRegistries installed in the cluster and loop thru them
    - get most of the subscription info from the operandRegistry
      - operandRegistry DOES NOT have version info, use the cache to get the head of channel version (at this point in time) so if someone did install something from the operandRegistry we KNOW which version (IN THEORY would be installed)
      - add/merge an entry to the ISC

```
operators:
- catalog: quay.io/huizenga/cs:heads-only
  packages:
  - channels:
    - name: v3
    name: ibm-licensing-operator-app
    versions:
    - 1.11.0
  - channels:
    - name: v3
    name: ibm-mongodb-operator-app
    versions:
    - 1.9.0
  - channels:
    - name: v3
    name: ibm-cert-manager-operator
    versions:
    - 3.16.0
  - channels:
    - name: v3
    name: ibm-iam-operator
    versions:
    - 3.12.2
  - channels:
    - name: v3
    name: ibm-healthcheck-operator-app
    versions:
    - 3.15.0
  ```
