### ISSUE TITLE
[RFE] split out release image into a new namespace/image name.

### ISSUE THREAD

**Issue by ianwatsonrh** [openshift/oc-mirror#319]
Currently all images are mirrored to openshift/release.

When using the Update Service, it is required to split the release image into a separate namespace/image such as openshift/release-images.

The Update Service is then pointed to this separate namespace, for example. 
```
apiVersion: updateservice.operator.openshift.io/v1
kind: UpdateService
metadata:
  name: update
spec:
  replicas: 2
  releases: registry.example.com/openshift/release-images
  graphDataImage: ${GRAPH_DATA_IMAGE}
```

If the update image is pointed to the openshift/release in this case, then the operator will try and inspect every image and which throws a out of memory.

This is subtly highlighted in the oc commands where it moves the release-image to a new repository but not explained. 
```
oc adm release mirror -a ${LOCAL_SECRET_JSON}  \
     --from=quay.io/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE}-${ARCHITECTURE} \
     --to=${LOCAL_REGISTRY}/${LOCAL_REPOSITORY} \
     --to-release-image=${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}:${OCP_RELEASE}-${ARCHITECTURE}
```
