### ISSUE TITLE
[BUG]: ICSP generated during mirror to disk produce in invalid source in the repository digest mirror

### ISSUE THREAD

**Issue by jpower432** [openshift/oc-mirror#322]
# Version

```console
$ oc-mirror version
Current main (commit d8db929f21799cfd24eb50dfa5fd43341c5e2a99)
```

# What happened?

`oc-mirror` ran as expected, but created an ICSP that looked like this:
```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: generic-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - localhost:5000/operator-framework
    source: operator-framework
```

# What you expected to happen?

The ICSP should look like this
```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: generic-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - localhost:5000/operator-framework
    source: quay.io/operator-framework
```

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ ./bin/oc-mirror --from out/mirror_seq1_000000.tar docker://localhost:5000 --log-level=debug --dest-use-http
```

# Anything else we need to know?

This only happen using a disk to mirror workflow

# References

Enter text here.
