### ISSUE TITLE
[RFE] ability to accept a reference to an operator catalog by a file based catalog directory/file in addition to actual image

### ISSUE THREAD

**Issue by joehuizenga** [openshift/oc-mirror#332]
In looking at the imageset-config-ref.yaml file today it looks like the operators section contains an array of operator catalogs and requires the catalog to be a container image.  It would be a great addition if the catalog could also point to a file based catalog directory or json yaml file without needed to actually be "baked" into a container image

Today
```
mirror:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8 # References entire catalog
      headsOnly: true # References latest version of each operator in catalog (true is the default value and can be omitted)
```

New feature
```
mirror:
    - catalog: file://<directory> or actual fbc.json/yaml file # References entire catalog
      headsOnly: true # References latest version of each operator in catalog (true is the default value and can be omitted)
```

**Comment by afflom** [comment]
I like the flexibility that this RFE suggests. To overcome the challenge that @jpower432 highlights, I suggest the following approach:

Create a new nested struct called something like `raw_fbc`, that has all of the same elements as the existing `catalog` struct, but with elements that allow a user to specify a raw fbc and a base image to build it with: https://github.com/openshift/oc-mirror/blob/41752468247a9337091b5979faee915154633cc4/pkg/config/v1alpha2/config_types.go#L65 

I consider this to be a very advanced use case, so creating a new struct is appealing to not disrupt the selection mechanisms within the current `catalog` struct.

Thoughts @jpower432 @joehuizenga ?

**Comment by joehuizenga** [comment]
@afflom @jpower432 sorry for the delay,  I am still wondering if it makes it cleaner to keep the idea of the catalog input to be  either an image or file and then add some sort of new struct called something like `build_info` and this struct could contain things like the opm image to use and maybe other elements like the catalogSourceName, or maybe even a dockerfile to use to build the new catalog?

**Comment by joehuizenga** [comment]
Hi @afflom @jpower432 just circling back to this topic as I think 4.11 feature freeze is sometime this month.  We were hoping not to have to build "intermediate" catalog images just to drive the oc-mirror cmd if possible. I could take a pass at providing more details if that would help

**Comment by jpower432** [comment]
Hi @joehuizenga, my apologies for missing your previous message. I do not believe that we will be able to fit this feature into our 4.11 development without an external contribution. If possible, could you provide more information about the specific use case and proposed solution? 

cc @dinhxuanvu

**Comment by joehuizenga** [comment]
Hi @jpower432 @afflom @dinhxuanvu  here is a mocked up sample of an ISC with "buildInfo" added just to kinda get the idea.  

We are internally discussing the option of making an external code contribution and wondering what the timeline for this code contribution would need to be to get it into 4.11. I think feature freeze is sometime towards the end of this month but when would the code need to be delivered?

```
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8 # References entire catalog
      full: true # AllPackages can be set to pull a full catalog and must be set to filter packages
      packages:
        - name: rhacs-operator
          startingVersion: '3.67.0'
          channels:
            - name: 'latest'
    - catalog: file://<path> # References entire catalog as a directory vs an image
      full: true # AllPackages can be set to pull a full catalog and must be set to filter packages
      buildInfo: # Additional data used to build the catalog source image and manifest
        baseImage: registry.redhat.io/redhat/ose-opm.....:v4.8
        targetImageName: <your name>
        catalogSourceName: my-custom-name    
      packages:
        - name: ibm-operator-a
          startingVersion: '3.67.0'
          channels:
            - name: 'v3.67'
```
     
  We have a requirement where we need to be able to manipulate a FBC prior to using it as a catalog specified in a imageSetConfig. We wanted to avoid having to add "container image building" as part of our process of manipulating an FBC just so we could then use this intermediate image as input defined in an ISC to drive oc-mirror.
  
  We are adding unique metadata to our initial FBC that we want to "pre-process" to help us reduce the number of relatedImages that need to be mirrored to the absolute minimum.  In our case, we have the same operator that can manage a set of different relatedImages based on what a customer has purchased,  so we are looking for a way to pre-process the comprehensive list of relatedImaged down to just what a customer is "entitled" to, not the full list.  We can do the pre-processing with a client based app by just manipulating the json. This json is still a smaller valid fbc and this is what we would like to use as the input to oc-mirror vs having to build a container image for it.

From prior discussion in this issue, it sounds like you expect a catalog image so you can inspect it to identify the opm base image you need to build up a catalog image for disconnected. I am proposing that if we include something like "buildInfo" as an alternate way to provide this information.

I am also proposing that we provide a way to also allow the ISC to define both the catalogSourceName and target imageName in somthing like a "buildInfo" section.  We need this type of information to make in easier for customers that have already installed 1 to N catalogSources in their cluster and have active subscriptions created with very specific catalogSource names that we would like to control. If we have the ability to declare this catalogSourceName, we could preserve it and would not have to add some sort of subscription migration tooling/process to help a customer migrate.
