### ISSUE TITLE
Bug 2055579 - [RFE] Add the ability in oc-mirror to create a (single) custom index to mirror operator packages from different catalog sources

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#352]
From: https://bugzilla.redhat.com/show_bug.cgi?id=2055579

Description of problem:

For the Telco RH GitOps ZTP solutions, it is desirable to have just a single operator index instead of four different operator indexes (i.e. "community-operator-index" "redhat-operator-index" "certified-operator-index" "redhat-marketplace-index"). This could decrease the CPU usage of the RH ZTP GitOps solution greatly.

Ideally, would be really nice if this can be accomplished in a declarative way using the same ImageSetConfiguration.yaml.

```
apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: bastion-aio2-8a.e2e.bos.redhat.com:8443/ocp9
mirror:
  ocp:
    channels:
      - name: candidate-4.10
        versions:
          - '4.10.0-rc.2'
    graph: false
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.9
      headsOnly: false
      packages:
        - name: local-storage-operator
        - name: ocs-operator
        - name: performance-addon-operator
        - name: ptp-operator
        - name: sriov-network-operator
        - name: advanced-cluster-management
        - name: openshift-gitops-operator
    - catalog: registry.redhat.io/redhat/certified-operator-index:v4.9
      headsOnly: false
      packages:
        - name: sriov-fec
#        - name: n3000
    - catalog: registry.redhat.io/redhat/community-operator-index:v4.9
      headsOnly: false
      packages:
        - name: hive-operator
```

oc-mirror --config imageset-config-ztp-catalog.yaml docker://bastion-aio2-8a.e2e.bos.redhat.com:8443/ocp9

IIUC, ^^ ImageSetConfiguration creates four different indexes in the disconnected registry, but we are looking for a way to mirror the packages to a single index, and thus catalog in OCP, using the same yaml file.

For a sample procedure to achieve this using opm tool, you may follow the procedure described here: https://docs.google.com/document/d/1M4FDhSR-GQ7-KV3BSY9ZZxt6e2M9rbOV-h-SDIgBKK8/.
