### ISSUE TITLE
Using catalog image with digest causes error

### ISSUE THREAD

**Issue by nschambu** [openshift/oc-mirror#423]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-1-g1f3f725", GitCommit:"1f3f725", GitTreeState:"clean", BuildDate:"2022-04-18T14:02:05Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"linux/amd64"}

```

# What happened?

I see an error when using an image and digest in an ImageSetConfiguration instead of an image and tag.

# What did you expect to happen?

I expected to be able to use either `image:tag` or `image@digest` in my ImageSetConfiguration.

# How to reproduce it (as minimally and precisely as possible)?

1. Create a valid ImageSetConfiguration using `image:tag`

```yaml
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: localhost:5000/test:latest # Stores metadata in an image
    skipTLS: true # Disable TLS certificate checking or use plain HTTP
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8 # References entire catalog
      full: true # AllPackages can be set to pull a full catalog and must be set to filter packages
      packages:
        - name: rhacs-operator
          startingVersion: '3.67.0'
          channels:
            - name: 'latest'
```

2. Verify that the oc-mirror request is successful:

```console
$ oc-mirror --config test-catalog.yaml file://archive/
```

3. Clean up that request and get the digest for the catalog (I'm using skopeo)

```console
$ skopeo inspect docker://registry.redhat.io/redhat/redhat-operator-index:v4.8 | jq .Digest
"sha256:b9cd0cbfb0a2552866565864779e06f5a8f09838a2c8d7597be47c600d9e601f"
```

4. Update the ImageSetConfiguration to use `image@digest`:

```yaml
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: localhost:5000/test:latest # Stores metadata in an image
    skipTLS: true # Disable TLS certificate checking or use plain HTTP
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index@sha256:b9cd0cbfb0a2552866565864779e06f5a8f09838a2c8d7597be47c600d9e601f # References entire catalog
      full: true # AllPackages can be set to pull a full catalog and must be set to filter packages
      packages:
        - name: rhacs-operator
          startingVersion: '3.67.0'
          channels:
            - name: 'latest'
```

5. Attempt to run the mirror command:

```console
oc-mirror --config test-catalog.yaml file://archive
INFO Found: archive/oc-mirror-workspace/src/publish 
INFO Found: archive/oc-mirror-workspace/src/v2    
INFO Found: archive/oc-mirror-workspace/src/charts 
INFO No metadata detected, creating new workspace 
WARN[0016] DEPRECATION NOTICE:
Sqlite-based catalogs and their related subcommands are deprecated. Support for
them will be removed in a future release. Please migrate your catalog workflows
to the new file-based catalog format. 
wrote mirroring manifests to archive/oc-mirror-workspace/operators.1650377358/manifests-redhat-operator-index

To upload local images to a registry, run:

	oc adm catalog mirror file://redhat/redhat-operator-index@sha256:b9cd0cbfb0a2552866565864779e06f5a8f09838a2c8d7597be47c600d9e601f REGISTRY/REPOSITORY
error: repository name must have at least one component
```

# Anything else we need to know?

I've been asked to also create a Bugzilla entry for this and will need some assistance with it.

# References

Enter text here.
