### ISSUE TITLE
[BUG] OCP release images are not being written to the correct repository when using disk to mirror

### ISSUE THREAD

**Issue by jpower432** [openshift/oc-mirror#439]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-19-ga31e562", GitCommit:"a31e562f", GitTreeState:"dirty", BuildDate:"2022-04-29T17:20:24Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

Release images must be separated from their content images in order to be used with OSUS. In mirror-to-mirror workflow, the release-images are written properly to the `release-images` repo. However, in the mirror-to-disk / disk-to-mirror worflows the release images are still being written to the `release` repo.

# What did you expect to happen?

The release images to always be written to `release-images`

# How to reproduce it (as minimally and precisely as possible)?

```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: metadata
mirror:
  platform:
    channels:
    - name: stable-4.9 
```

```console
$ ./bin/oc-mirror --config ~/configs/imageset-config.yaml.49 file://release-test
$ ./bin/oc-mirror --from release-test/ docker://locahost:5000
$ podman pull localhost:5000/openshift/release-images:4.9.29-x86_64
```

# Anything else we need to know?

Enter text here.

# References

/kind bug
