### ISSUE TITLE
Mirroring images to Red Hat Quay mirror registry fails with error 'Cannot create organization'

### ISSUE THREAD

**Issue by waljaber** [openshift/oc-mirror#441]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"0", Minor:"1", GitVersion:"v0.1.0", GitCommit:"63d070c19e8f5b6c84b0b3339102c307ad1cac05", GitTreeState:"clean", BuildDate:"2022-03-31T17:05:48Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?
```console
INFO Checking push permissions for registry-host:8443
DEBUG Using image registry-host:8443/ocp4/oc-mirror to check permissions
error: error checking push permissions for registry-host:8443: creating push check transport for registry-host:8443 failed: GET https://registry-host:8443/v2/auth?scope=repository%3Aocp4%2Foc-mirror%3Apush%2Cpull&service=registry-host%3A8443: UNSUPPORTED: Cannot create organization; map[]
```

# What did you expect to happen?

I expect the oc-mirror utility to be able to push images onto the Red Hat Quay mirror-registry

# How to reproduce it (as minimally and precisely as possible)?

In a partially disconnected environment, I am trying to mirror images to a quay instance, and save the imageset-metadata on the same mirror registry
I used this Image Set Configuration manifest
```yaml
apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: registry-host/ocp4/metadata:latest
mirror:
  ocp:
    channels:
    - name: stable-4.9
      versions: 
      - '4.9.28'
```

And I issued this command to start the mirroring process.
```console
$  oc-mirror --config=isc.yaml docker://registry-host:8443/ocp4 --log-level debug
```

# Anything else we need to know?
The name `registry-host` is an alias i am using to report this issue, in my environment the registry is using a FQDN that is resolvable through DNS A record, and has a reverse DNS record as well.

I installed the `mirror-registry version v1.1.0` by running the following command.
```console
$ ./mirror-registry install -v \
 --quayHostname $(hostname -f)  --quayRoot $(pwd)/data \
 --sslCert server.crt --sslKey server.key
```

I verified the image registry is up by navigating to the URL , and I have verified that I am able to push images to it.
```bash
$ podman pull docker.io/hello-world
$ podman tag docker.io/hello-world registry-host:8443/testing/hello-world:v1
$ podman push registry-host:8443/testing/hello-world:v1
```

**Comment by waljaber** [comment]
Just as a follow up I was able to mirror images when I used the organization `testing` which I created when I did the sanity test for the registry by running the following command
```bash
podman push registry-host:8443/testing/hello-world:v1
```

In this successful mirroring run I used this image set configuration manifest.
> Note the change of organization from 'ocp4' to 'testing' in `storageConfig.registry.imageURL`

```yaml
apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: registry-host:8443/testing/metadata:latest
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.9
    headsOnly: false
    packages:
    - name: file-integrity-operator
      channels:
      - name: release-0.1
      startingVersion: '0.1.22'
```

I ran the following oc-mirror command and it downloaded, and pushed all the images without failure
```console
oc-mirror --config=isc.yaml docker://re1-oc4-rv-bh01.crplmgt.com.sa:8443/testing --log-level debug
```

**Comment by jpower432** [comment]
@waljaber Thanks for submitting this issue. Sorry for the delay in responding, it took a bit to reproduce, but we were finally able to.

/kind bug

**Comment by jharmison-redhat** [comment]
@waljaber Can you confirm the version of the mirror-registry you're using?

I was unable to reproduce using the latest release versions of both [oc-mirror](https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/latest-4.10/oc-mirror.tar.gz) and [mirror-registry](https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/mirror-registry/1.1.0/mirror-registry.tar.gz).

I generated TLS certificates for the mirror-registry and ran the installer with this command:

```sh
./mirror-registry install --initUser admin --initPassword <redacted> --quayHostname registry.internal.disco.redhat4govaws.io:443 --quayRoot /etc/quay/data --sslCert /etc/quay/pki/ssl.cert --sslKey /etc/quay/pki/ssl.key --sslCheckSkip
```

I set up my pull secret for oc-mirror by merging the following with the pull secret from console.redhat.com:
```json
{
  "auths": {
    "registry.internal.disco.redhat4govaws.io": {
      "auth": "<redacted>",
      "email": "admin@disco.redhat4govaws.io"
    },
    "registry.internal.disco.redhat4govaws.io:443": {
      "auth": "<redacted>",
      "email": "admin@disco.redhat4govaws.io"
    }
  }
}
```

I used this ImageSetConfiguration:
```yaml
apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: registry.internal.disco.redhat4govaws.io/ocp4/metadata:latest
mirror:
  ocp:
    channels:
    - name: stable-4.9
      versions: 
      - '4.9.28'
```

And then I ran the following to mirror everything inside a nested namespace on the mirror-registry:
```sh
./oc-mirror --config ~/imageset-config.yml docker://registry.internal.disco.redhat4govaws.io/oc-mirror
```

#### **NOTE**: I am redoing this to publish to the same namespace as the metadata, to make sure there's not some weird edge case here.

My mirror ran fine:
```text
<large log from mirroring>
time="2022-05-06T14:00:58Z" level=debug msg="rebuilding catalog images"
time="2022-05-06T14:00:58Z" level=debug msg="No catalogs found in archive, skipping catalog rebuild"
time="2022-05-06T14:00:58Z" level=info msg="Wrote ICSP manifests to oc-mirror-workspace/results-1651845318"
time="2022-05-06T14:00:58Z" level=info msg="CatalogSource and ICSP install not implemented"
time="2022-05-06T14:00:58Z" level=debug msg="Pushing metadata to registry at registry.internal.disco.redhat4govaws.io/oc-mirror/oc-mirror:a1941ced-6ec0-4b9d-b691-a53d930e723e"
```

And just to be sure, I installed OpenShift from it:
```text
<large log from installation>
time="2022-05-06T14:36:58Z" level=info msg="Install complete!"
time="2022-05-06T14:36:58Z" level=info msg="To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/home/ec2-user/install/auth/kubeconfig'"
time="2022-05-06T14:36:58Z" level=info msg="Access the OpenShift web-console here: https://console-openshift-console.apps.disco.redhat4govaws.io"
time="2022-05-06T14:36:58Z" level=info msg="Login to the console with user: \"kubeadmin\", and password: \"c5jTb-TM8FA-iAijt-WaApH\""
time="2022-05-06T14:36:58Z" level=debug msg="Time elapsed per stage:"
time="2022-05-06T14:36:58Z" level=debug msg="           cluster: 4m10s"
time="2022-05-06T14:36:58Z" level=debug msg="         bootstrap: 32s"
time="2022-05-06T14:36:58Z" level=debug msg="Bootstrap Complete: 11m39s"
time="2022-05-06T14:36:58Z" level=debug msg="               API: 2m12s"
time="2022-05-06T14:36:58Z" level=debug msg=" Bootstrap Destroy: 50s"
time="2022-05-06T14:36:58Z" level=debug msg=" Cluster Operators: 14m11s"
time="2022-05-06T14:36:58Z" level=info msg="Time elapsed: 31m31s"
```

**Comment by waljaber** [comment]
Hello @jharmison-redhat thank you for engaging with me on this issue, I am using the mirror-registry version `1.1.0` 

```console
$ ./mirror-registry --version

   __   __
  /  \ /  \     ______   _    _     __   __   __
 / /\ / /\ \   /  __  \ | |  | |   /  \  \ \ / /
/ /  / /  \ \  | |  | | | |  | |  / /\ \  \   /
\ \  \ \  / /  | |__| | | |__| | / ____ \  | |
 \ \/ \ \/ /   \_  ___/  \____/ /_/    \_\ |_|
  \__/ \__/      \ \__
                  \___\ by Red Hat
 Build, Store, and Distribute your Containers

mirror-registry version v1.1.0
```

I want to note few things for your attention, I see that you issued the `oc-mirror` command to an organization named `oc-mirror`, while your image set configuration manifest has the metadata set to another organization which is `ocp4`. 

When I got the error I used the same organization for both mirroring images, and image set metadata.

The error was:
```console
oc-mirror --config=isc.yaml docker://registry-host:8443/ocp4 --log-level debug
INFO Checking push permissions for registry-host:8443

DEBUG Using image registry-host:8443/ocp4/oc-mirror to check permissions

error: error checking push permissions for registry-host:8443: creating push check transport for registry-host:8443 failed: GET https://registry-host:8443/v2/auth?scope=repository%3Aocp4%2Foc-mirror%3Apush%2Cpull&service=registry-host%3A8443: UNSUPPORTED: Cannot create organization; map[]
```

Furthermore I ran the same oc-mirror command you used which has the organization set to `oc-mirror` (please note the image set configuration was not changed, it was still using `ocp4`) and that worked!?
```console
oc-mirror --config=isc.yaml docker://registry-host:8443/oc-mirror --log-level debug
INFO Checking push permissions for registry-host:8443
DEBUG Using image registry-host:8443/oc-mirror/oc-mirror to check permissions
workspace: ./mirrortmp3558264268
DEBUG Using registry backend at location registry-host:8443/ocp4/metadata:latest
DEBUG Checking for existing metadata image at registry-host:8443/ocp4/metadata:latest
INFO Found: oc-mirror-workspace/src/publish
INFO Found: oc-mirror-workspace/src/v2
INFO Found: oc-mirror-workspace/src/charts
INFO Downloading requested release 4.9.28
DEBUG Starting release download for version 4.9.28
DEBUG Using /usr/bin/unpigz to decompress
DEBUG Using /usr/bin/unpigz to decompress
INFO Downloading requested release 4.9.28
DEBUG Starting release download for version 4.9.28
DEBUG Using /usr/bin/unpigz to decompress
DEBUG Using /usr/bin/unpigz to decompress
DEBUG Using /usr/bin/unpigz to decompress
DEBUG Using /usr/bin/unpigz to decompress
DEBUG Using /usr/bin/unpigz to decompress
DEBUG Using /usr/bin/unpigz to decompress
info: Mirroring 141 images to file://openshift/release ...
```

Which lead me to believe this might be an issue with `oc-mirror` utility that it can't mirror the images to the same organization used to store the image set metadata. 
<br>

So to further isolate the issue I deployed a docker registry using the following podman command:
```bash
sudo podman run --name secure-registry -d \
  -v /opt/registry/docker/data:/var/lib/registry:Z \
  -v /opt/registry/docker/cert/:/certs:Z \
  -e REGISTRY_HTTP_ADDR=0.0.0.0:443 \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/server.key \
  -p 443:443 \
  docker.io/registry:2
```
> Note: I deployed this instance without authentication. 

And edited my imageSetConfiguration manifest to point to the deployed docker registry with the repo `ocp4`
```yaml
apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: docker-registry-host/ocp4/metadata:latest
mirror:
  ocp:
    channels:
    - name: stable-4.9
      versions: 
      - '4.9.28'
```

I ran an `oc-mirror` command that mirrored the images to the same orgnization (i.e. `ocp4`) and that also worked!

```console
$ oc-mirror --config=isc2.yaml docker://docker-registry-host/ocp4 --log-level debug
INFO Checking push permissions for docker-registry-host
DEBUG Using image docker-registry-host/ocp4/oc-mirror to check permissions
workspace: ./mirrortmp1064302921
DEBUG Using registry backend at location docker-registry-host/ocp4/metadata:latest
DEBUG Checking for existing metadata image at docker-registry-host/ocp4/metadata:latest
DEBUG looking for metadata file at "publish/.metadata.json"
INFO Found: oc-mirror-workspace/src/publish
INFO Found: oc-mirror-workspace/src/v2
INFO Found: oc-mirror-workspace/src/charts
INFO Downloading requested release 4.9.28
DEBUG Starting release download for version 4.9.28
DEBUG Using /usr/bin/unpigz to decompress
DEBUG Using /usr/bin/unpigz to decompress
DEBUG Using /usr/bin/unpigz to decompress
DEBUG Using /usr/bin/unpigz to decompress
DEBUG Using /usr/bin/unpigz to decompress
DEBUG Using /usr/bin/unpigz to decompress
info: Mirroring 141 images to file://openshift/release ...
```
***
So I concluded that the `oc-mirror` utility has this issue with the `quay mirror-registry` only when the same organization is used for both mirroring images, and storing metadata, given that the organization didn't exist in the `quay mirror-registry` previously.


I hope this investigation was helpful to you, :D

**Comment by jharmison-redhat** [comment]
I'm actually unable to get that behavior.

ImageSetConfig:
```yaml
apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: registry.internal.disco.redhat4govaws.io/ocp4/metadata:latest
mirror:
  ocp:
    channels:
    - name: stable-4.9
      versions:
      - '4.9.28'
```

```
$ ./oc-mirror version
Client Version: version.Info{Major:"0", Minor:"1", GitVersion:"v0.1.0", GitCommit:"c35f1e1859003e75064d8ed0f1c372db820f001a", GitTreeState:"clean", BuildDate:"2022-04-21T13:56:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
$ ./oc-mirror --config /home/ec2-user/imageset-config.yml  docker://registry.internal.disco.redhat4govaws.io/ocp4
<lots of push output>
```

From the logs:
```
time="2022-05-07T15:00:33Z" level=info msg="Checking push permissions for registry.internal.disco.redhat4govaws.io"
time="2022-05-07T15:00:33Z" level=debug msg="Using image registry.internal.disco.redhat4govaws.io/ocp4/oc-mirror to check permissions"
time="2022-05-07T15:00:33Z" level=debug msg="Using registry backend at location registry.internal.disco.redhat4govaws.io/ocp4/metadata:latest"
time="2022-05-07T15:00:33Z" level=debug msg="Checking for existing metadata image at registry.internal.disco.redhat4govaws.io/ocp4/metadata:latest"
time="2022-05-07T15:00:33Z" level=info msg="Creating directory: oc-mirror-workspace/src/publish"
time="2022-05-07T15:00:33Z" level=info msg="Creating directory: oc-mirror-workspace/src/v2"
time="2022-05-07T15:00:33Z" level=info msg="Creating directory: oc-mirror-workspace/src/charts"
time="2022-05-07T15:00:33Z" level=info msg="Downloading requested release 4.9.28"
time="2022-05-07T15:00:34Z" level=debug msg="Starting release download for version 4.9.28"
time="2022-05-07T15:00:35Z" level=debug msg="Using /usr/bin/unpigz to decompress"
time="2022-05-07T15:00:36Z" level=debug msg="Using /usr/bin/unpigz to decompress"
time="2022-05-07T15:00:37Z" level=debug msg="Using /usr/bin/unpigz to decompress"
time="2022-05-07T15:00:38Z" level=debug msg="Using /usr/bin/unpigz to decompress"
time="2022-05-07T15:00:39Z" level=debug msg="Using /usr/bin/unpigz to decompress"
time="2022-05-07T15:00:39Z" level=debug msg="Using /usr/bin/unpigz to decompress"
time="2022-05-07T15:02:46Z" level=debug msg="starting image association"
time="2022-05-07T15:02:46Z" level=info msg="Downloading 1 image(s) to oc-mirror-workspace/src"
<lots of logs trimmed as it pushed>
time="2022-05-07T15:09:51Z" level=debug msg="rebuilding catalog images"
time="2022-05-07T15:09:51Z" level=debug msg="No catalogs found in archive, skipping catalog rebuild"
time="2022-05-07T15:09:51Z" level=info msg="Wrote ICSP manifests to oc-mirror-workspace/results-1651935844"
time="2022-05-07T15:09:51Z" level=info msg="CatalogSource and ICSP install not implemented"
time="2022-05-07T15:09:51Z" level=debug msg="Pushing metadata to registry at registry.internal.disco.redhat4govaws.io/ocp4/oc-mirror:9fd231bd-926e-4e13-8a93-c0098940f4f9"
```

And that's with mirror-registry 1.1.0, installed with the same command as above and using the same pull-secret setup as I listed above as well. I am unsure what about your configuration could possibly be causing you to have this issue at the moment. I know that the way that push permissions were checked has been tweaked slighly in the 4.11/main branches for oc-mirror. Would you be willing to see if you can reproduce using the [latest preview build](https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp-dev-preview/latest-4.11/oc-mirror.tar.gz)? You'll need to adjust your ImageSetConfiguration a bit:

```yaml
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: registry-host:8443/ocp4/metadata:latest
mirror:
  platform:
    channels:
    - name: stable-4.9
      minVersion: '4.9.28'
      maxVersion: '4.9.28'
```
