### ISSUE TITLE
[RFE] Support a locally addressable filesystem representation of an operator catalog image as an input source in an ImageSetConfig

### ISSUE THREAD

**Issue by joehuizenga** [openshift/oc-mirror#446]
This RFE is asking that oc-mirror accept multiple operator catalog image-representations or “types” as input via the catalog element in an ISC. 

**Specifically that it supports at least one local filesystem "type"**.

These “types” could be similar to what tools like [skopeo](https://github.com/containers/skopeo#skopeo) use today (ie: docker://, oci://, dir://)

```
skopeo copy docker://registry.redhat.io/redhat/certified-operator-index:v4.10 oci:.
```

Currently oc-mirror only allows a user to specify an operator catalog image via a string which is a reference to a catalogSource container image in a container registry.

```
mirror:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8 
```

There are customer scenarios where being able to specify the catalog input to oc-mirror via an accessible filesystem path (ie: type =  oci or type = dir…) provides a more streamlined customer experience.

Tomorrow, possible transport type based image representations to show concept:

```
mirror:
    - catalog: “docker://registry.redhat.io/redhat/redhat-operator-index:v4.8”  #whats there today
    - catalog: “oci:<relative path to accessible filesystem representation of the image >”   #possible filesystem based image representations
    - catalog: “dir:<relative path to accessible filesystem representation of the image>”
    - catalog: “tgz:<relative path to accessible filesystem representation of the image>”
```

In all of the input types, a catalog image contains a specific version of opm code that “knows” how to serve the grpc interface and “knows” how to interact with the “File Based Catalog” that was packaged in the image when it was built.

The oc-mirror tooling accepts the container image as input and will only modify the “FBC” layers of this image.  It preserves the layers that represent the specific version of opm that “works”, by only modifying the “backend/fbc” layers of this image. 

oc-mirror does not have to concern itself with making sure the image it produces is using the “right” opm binary. It just uses what was already present in the image.

The core logic of oc-mirror should remain the same once the input has been loaded based on it’s type.
