### ISSUE TITLE
[BUG] image pruning operation attempts to delete release images in wrong location

### ISSUE THREAD

**Issue by jpower432** [openshift/oc-mirror#447]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-29-g4849560", GitCommit:"4849560f", GitTreeState:"dirty", BuildDate:"2022-05-04T21:26:46Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

When attempting to prune an OCP release from an imageset the target repository is incorrect resulting in a 404.

# What did you expect to happen?

The release images to be pruned from the correct repository.

# How to reproduce it (as minimally and precisely as possible)?

```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: metadata
mirror:
  platform:
    channels:
    - name: stable-4.9
```
```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: metadata
mirror:
  platform:
    channels:
    - name: stable-4.10
```

Mirror with the first configuration and then again with the second to reproduce.
```console
$ ./bin/oc-mirror --config imageset-config.yaml docker://localhost:5000
```

# Anything else we need to know?

# References

Enter text here.
