### ISSUE TITLE
[BUG] Mirroring a package with a range and heads-only channel results in "Version is empty"

### ISSUE THREAD

**Issue by jpower432** [openshift/oc-mirror#465]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-36-g7bde4c7", GitCommit:"7bde4c7b", GitTreeState:"clean", BuildDate:"2022-05-16T13:31:03Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

Most likely an edge cases, but it exposes an issue with how the heads-only metadata is being recorded for package with
multiple channel configurations.
When trying to mirror a package with some channels having set ranges and another channel with heads-only,
the heads-only channel is not recorded properly. In some (possibly obscure) cases, this can lead to error during
future include config update.

# What did you expect to happen?

The `minVersion` to be recorded correctly and not error when trying to update.

The heads only channel being recorded properly despite other channels having version information set.

# How to reproduce it (as minimally and precisely as possible)?

Two configs need to be used to reproduce:
```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: test
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
      packages:
        - name: quay-operator
          channels:
          - name: stable-3.6
          - name: quay-v3.5
            minVersion: 3.5.7
```

```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: test
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
      packages:
        - name: quay-operator
          channels:
          - name: stable-3.6
```

```console
$ oc-mirror --config imageset-config-1.yaml file://out
$ oc-mirror --config imageset-config-2.yaml file://out --dry-run
```

# Anything else we need to know?

# References

Pull Request will be submitted today
