### ISSUE TITLE
[BUG] Empty channels are not pruned from catalog when full is set to true

### ISSUE THREAD

**Issue by jpower432** [openshift/oc-mirror#471]
# Version

```console
$ oc-mirror version
Commit on main b4ec5c3b2856678e11ad212db6f306e817eb0b10
```

# What happened?

Error occurred when mirroring a package with a minimum version at the package level with full set to true.

```
Found: oc-mirror-workspace/src/publish
Found: oc-mirror-workspace/src/v2
Found: oc-mirror-workspace/src/charts
error: error updating include config: invalid index:
└── invalid package "cluster-logging":
    ├── invalid channel "stable-5.2":
    │   └── channel must contain at least one bundle
    └── invalid channel "stable-5.3":
        └── channel must contain at least one bundle
```

# What did you expect to happen?

Empty channels to be removed from the index.

# How to reproduce it (as minimally and precisely as possible)?

```
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    skipTLS: false
    imageURL: localhost:5001/test:latest
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
    full: true
    packages:
    - name: cluster-logging
      minVersion: '5.4.1-24'
```

```console
$ oc-mirror --config ~/configs/imageset-config.yaml docker://locahost:5001
```

# Anything else we need to know?

# References

https://bugzilla.redhat.com/show_bug.cgi?id=2087764
