### ISSUE TITLE
[BUG] oc-mirror authentication error intermittently with "unauthorized: Access to the requested resource is not authorized"

### ISSUE THREAD

**Issue by jpower432** [openshift/oc-mirror#472]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.11.0-202205101549.p0.gfa91e43.assembly.stream-fa91e43", GitCommit:"fa91e43d39da0630296fe74cfe756fc0ed7d6756", GitTreeState:"clean", BuildDate:"2022-05-10T18:07:11Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

This error is received intermittently.
```
error: unable to push registry.redhat.io/advanced-cluster-security/rhacs-roxctl-rhel8: failed to retrieve blob sha256:e3bdc6c23d58940ba064805bbbc9b5842b2cd11bba834312f00245c1935e5826: unauthorized: Access to the requested resource is not authorized
error: unable to push registry.redhat.io/advanced-cluster-security/rhacs-roxctl-rhel8: failed to retrieve blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1: unauthorized: Access to the requested resource is not authorized
```

# What did you expect to happen?

No error

# How to reproduce it (as minimally and precisely as possible)?

```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.9
      packages:
        - name: elasticsearch-operator
          minVersion: '5.4.1-24'
          channels:
            - name: stable
        - name: rhacs-operator
          channels:
            - name: latest
              minVersion: '3.69.0'
```

```console
$ oc-mirror --config imageset.yaml file://
```

# Anything else we need to know?

Originally reported as BZ, duplicating here for project planning

# References

https://bugzilla.redhat.com/show_bug.cgi?id=2063154

/kind bug
