### ISSUE TITLE
oc-mirror skip-missing still returns a 404 error

### ISSUE THREAD

**Issue by jpower432** [openshift/oc-mirror#476]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-42-ge3e6bf9", GitCommit:"e3e6bf9f", GitTreeState:"clean", BuildDate:"2022-05-24T17:31:23Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?
 
`error parsing HTTP 404 response body: invalid character 'N' looking for beginning of value: "Not found\n"`

# What did you expect to happen?

No 404 error with skip-missing

# How to reproduce it (as minimally and precisely as possible)?

```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: metadata
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
      packages:
        - name: ptp-operator
          channels:
            - name: stable
          minVersion: '4.10.0-202205121158'
```
```console
$ oc-mirror --config ~/configs/imageset-config.yaml docker://localhost:5001 --skip-missing
```

# Anything else we need to know?

This happens because `oc-mirror` translates all tag references to digest and the library used to mirror supports tag references only currently.

# References

https://github.com/openshift/oc/pull/1105

https://bugzilla.redhat.com/show_bug.cgi?id=2089918
