### ISSUE TITLE
[BUG] helm chart and release signatures are written to a different results directory

### ISSUE THREAD

**Issue by jpower432** [openshift/oc-mirror#481]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-41-gf93ddac", GitCommit:"f93ddac6", GitTreeState:"clean", BuildDate:"2022-05-31T16:43:37Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

The chart output was written to a different results directory than the manifest output.
```
.
├── results-1654015879
│   └── charts
│       └── podinfo-5.0.0.tgz
└── results-1654015889
    ├── imageContentSourcePolicy.yaml
    └── mapping.txt
```

# What did you expect to happen?

The results to be written to one results directory.

# How to reproduce it (as minimally and precisely as possible)?

```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  helm:
    repositories:
      - name: podinfo
        url: https://stefanprodan.github.io/podinfo
        charts:
          - name: podinfo
            version: 5.0.0
```

```console
$ oc-mirror --config imageset-config.yaml.helm file://out
$ oc-mirror --from out/mirror_seq1_000000.tar docker://localhost:5001
```

# Anything else we need to know?

This does not occur with the mirror to mirror workflow.

# References

/kind bug
