### ISSUE TITLE
Unable to mirror from registry.redhat.io

### ISSUE THREAD

**Issue by cmasonrh** [openshift/oc-mirror#498]
# Version

```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-59-gc1cd759", GitCommit:"c1cd759", GitTreeState:"clean", BuildDate:"2022-07-27T19:05:42Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?
Unable to mirror from registry.redhat.io likely due to the change from V2 Schema 1 to V2 Schema 2.

Error:
```
error: unable to retrieve source image registry.redhat.io/amq7/amq-broker-rhel8 manifest sha256:ca9ee88c28373525732d18f87331b350dc3babf8c7291c9477435439f7a53f0e: unsupported: V2 schema 1 manifest digests are no longer supported for image pulls. Use the equivalent V2 schema 2 manifest digest instead. For more information see https://access.redhat.com/articles/6138332
```

# What did you expect to happen?

Expected operators configure in image-set to be mirrored locally. With no errors.

# How to reproduce it (as minimally and precisely as possible)?

```
./bin/oc-mirror --config imageset-config.yaml file://~/oc-mirror
```

```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 1
storageConfig:
  local:
    path: /home/cmason/tmp/oc-mirror
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.9
      full: true
      packages:
        - name: amq-broker-rhel8
          channels:
            - name: 7.x
            - name: 7.10.x
        - name: fuse-console
          channels:
            - name: 7.10.x
            - name: 7.11.x
            - name: 7.9.x
```

# References

Knowledgebase entry on change in schema. https://access.redhat.com/articles/6138332
