### ISSUE TITLE
resulting catalog pod with /configs/index.json: permission denied

### ISSUE THREAD

**Issue by haf-tech** [openshift/oc-mirror#502]
Using oc mirror to mirror the CatalogSources for a air-gapped/disconnected OpenShift installation.
After 
- mirroring successfully the images into an internal registry and 
- applying the generated manifest files (CatalogSource, ImageContextSourcePolicy etc)
- updating the pull secret into the global secrets
- the pods in openshift-marketplace pulls the images

but a start of the pods does not work.
The error message in the log of all the catalog source pods in `openshift-marketplace` is:

```
Error: load declarative config directory: open /configs/index.json: permission denied
Usage:
opm serve <source_path> [flags]
Flags:
--debug enable debug logging
-h, --help help for serve
-p, --port string port number to serve on (default "50051")
-t, --termination-log string path to a container termination log file (default "/dev/termination-log")
Global Flags:
--skip-tls skip TLS certificate verification for container image registries while pulling bundles or index
```

What is the root case and how to fix this?

# Versions
- OpenShift 4.10.22 

- oc cli
oc version
Client Version: 4.10.22
Server Version: 4.10.22
Kubernetes Version: v1.23.5+3afdacb

- oc mirror version
oc mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.11.0-202208020235.p0.g3c1c80c.assembly.stream-3c1c80c", GitCommit:"3c1c80ca6a5a22b5826c88897e7a9e5acd7c1a96", GitTreeState:"clean", BuildDate:"2022-08-02T04:04:36Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by haf-tech** [comment]
the root cause is
using the *latest* version of `oc-mirror` with OCP 4.10.x is not working.
Have to switch to oc-mirror version from `release-4.10` branch

**Comment by jpower432** [comment]
@haf-tech Would you be able to share a bit more about this failure? Specifically the imageset configuration. We have confirmed success using `oc-mirror` 4.11 to mirror the 4.10 catalog on an OCP 4.10 cluster running on the default RHEL 8 AMI. I was curious if a difference in the umask configuration could be causing this issue.

**Comment by haf-tech** [comment]
@jpower432 I do not have the same imageset, because I had to change little bit the format for the old version of oc-mirror
this is an old version, I should cover nearly the similar config, that I used with the latest oc-mirror version

```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  platform:
    graph: true
    channels:
       - name: stable-4.10 
         shortestPath: true
         minVersion: 4.10.22
         maxVersion: 4.10.26
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
      targetName: a-redhat-operator-catalog-platform-essentials
      packages:
        - name: elasticsearch-operator
          channels:
            - name: 'stable'
          minVersion: 5.5.0
        - name: cluster-logging
          channels:
            - name: 'stable'
          minVersion: 5.5.0
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
      targetName: a-redhat-operator-catalog-gitops
      packages:
        - name: openshift-gitops-operator
          channels:
            - name: 'gitops-1.6'
          minVersion: 1.6.0
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
      targetName: a-redhat-operator-catalog-test
      packages:
        - name: openshift-pipelines-operator-rh
          channels:
            - name: pipelines-1.7
          minVersion: 1.7.2
 

  additionalImages:
    - name: registry.redhat.io/openshift4/ose-cli:v4.10
    - name: registry.redhat.io/ubi9/ubi:latest
    - name: registry.redhat.io/rhel8/support-tools:latest
    - name: docker.io/bitnami/sealed-secrets-controller:v0.17.5

storageConfig:
  registry:
    imageURL: a-container-registry.com/mirror/oc-mirror

```
