### ISSUE TITLE
Exception in channel not included in imagesetconfiguration

### ISSUE THREAD

**Issue by rgordill** [openshift/oc-mirror#509]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.11.0-202208031306.p0.g3c1c80c.assembly.stream-3c1c80c", GitCommit:"3c1c80ca6a5a22b5826c88897e7a9e5acd7c1a96", GitTreeState:"clean", BuildDate:"2022-08-03T14:23:35Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"linux/amd64"}

```

# What happened?

It throws an exception.

```
Found: oc-mirror-workspace/src/publish
Found: oc-mirror-workspace/src/v2
Found: oc-mirror-workspace/src/charts
Found: oc-mirror-workspace/src/release-signatures
Adding graph data

The rendered catalog is invalid.

Run "oc-mirror list operators --catalog CATALOG-NAME --package PACKAGE-NAME" for more information.

error: error generating diff: channel fast: head "devworkspace-operator.v0.15.2-0.1661828401.p" not reachable from bundle "devworkspace-operator.v0.15.2"
```

# What did you expect to happen?

As channel fast is not selected in imageset-config.yaml, it should not throw an exception.

# How to reproduce it (as minimally and precisely as possible)?

imageset-config.yaml:

```yml
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: mirror.example.com:8443/mirror/oc-mirror-metadata
    skipTLS: true
mirror:
  platform:
    channels:
    - name: stable-4.11
      type: ocp
      minVersion: 4.11.0
      maxVersion: 4.11.1
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.11
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  - name: quay.io/edge-infrastructure/assisted-installer-agent:latest
  - name: quay.io/edge-infrastructure/assisted-installer:latest
  - name: quay.io/edge-infrastructure/assisted-installer-controller:latest
  blockedImages:
  - name: registry.redhat.io/rhel9-beta/tang-operator
  - name: registry.redhat.io/rhel9-beta/tang-operator-bundle
  - name: registry.redhat.io/openshift-service-mesh
  helm: {}
```

```console
oc-mirror --dest-skip-tls --config=./imageset-config.yaml   docker://mirror.example.com:8443
```

# Anything else we need to know?

The blockedImages is due to another issue in our registry repo with schema 2 v1.

# References

N/A
