### ISSUE TITLE
Mirroring to localhost results in unauthorized attempts to push to quay.io

### ISSUE THREAD

**Issue by dmc5179** [openshift/oc-mirror#513]
```console
oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.11.0-202209130958.p0.g3c1c80c.assembly.stream-3c1c80c", GitCommit:"3c1c80ca6a5a22b5826c88897e7a9e5acd7c1a96", GitTreeState:"clean", BuildDate:"2022-09-13T10:48:59Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

When using localhost as the mirroring endpoint, oc-mirror attempts to push images to quay.io which results in unauthorized push error messages.

```
error: unable to push quay.io/openshift-release-dev/ocp-v4.0-art-dev: failed to upload blob sha256:bacf4c9a03793fbbb179d8a644c65c23e46dbd9db4c9548c1a7dc08bc01ded9c: unauthorized: access to the requested resource is not authorized
error: unable to push quay.io/openshift-release-dev/ocp-v4.0-art-dev: failed to upload blob sha256:ee11329518be02dbd9573b28833cc496f3cc435ae594d51ce8ed9037df36dc56: unauthorized: access to the requested resource is not authorized
```

# What did you expect to happen?

Images to be mirrored to the registry running on localhost

# How to reproduce it (as minimally and precisely as possible)?

- set localhost as the storage config image location
- use localhost as the docker destination in the mirroring command

```console
oc-mirror --config /tmp/imageset-config.yaml --dest-skip-tls --continue-on-error docker://localhost:8443 
```

# Anything else we need to know?

Contents of imageset-config.yaml
```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: localhost:8443/mirror-state:latest # Stores metadata in an image
    skipTLS: true # Disable TLS certificate checking or use plain HTTP 
mirror:
  platform:
    channels:
      - name: stable-4.11 # References latest stable release
    graph: true # Include Cincinnati upgrade graph image in imageset
```
