### ISSUE TITLE
Error 401 when operations take more than 5min

### ISSUE THREAD

**Issue by fjcloud** [openshift/oc-mirror#526]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.11.0-202210262118.p0.g3c1c80c.assembly.stream-3c1c80c", GitCommit:"3c1c80ca6a5a22b5826c88897e7a9e5acd7c1a96", GitTreeState:"clean", BuildDate:"2022-10-27T00:32:32Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

```
error: error rendering new refs: render reference "registry.redhat.io/redhat/redhat-operator-index:v4.11": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.redhat.io/v2/redhat/redhat-operator-index/blobs/sha256:144af1563390e9a694f66e8065b32e12ab836b1412de7fdf423996a229b00d21: 401 Unauthorized - Server message: unauthorized: Access to the requested resource is not authorized
```

# What did you expect to happen?

When operations are too long i experience 401 error

# How to reproduce it (as minimally and precisely as possible)?

Use `cpulimit` to artificially make tasks longer

```console
$  cpulimit -l 1 ./oc-mirror --config config.yml docker://localhost:5000 --dest-skip-tls --dest-use-http --verbose 9
```

# Anything else we need to know?

my `config.yml`
```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: localhost:5000/metadata:latest
    skipTLS: true
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.11
      packages:
        - name: loki-operator
        - name: elasticsearch-operator
        - name: odf-operator
```

I suspect that after 5min auth with registry expire and there no refresh mecanism.
