### ISSUE TITLE
Mirroring a specific operator version that is not in the daft channel

### ISSUE THREAD

**Issue by Destorntw** [openshift/oc-mirror#538]
Hi team,
Hillay from the IGC PS,
In the past I had no problems mirroring a specific operator version from a channel that was not the daft channel. 
Since using the oc-mirror v4.11 binary it would auto-re-direct me to the dafulat channel and won't mirror (output errors) due to me asking for a package version that is not in the "default channel" set up by the catalog and operator maintainers as I understood.

With the advice of a developer from the team (former role) I tried using the oc-mirror v4.12 binary and still had errors (similar but different). 
How can I best work to advance this feature/bug in the cli?
Attaching my errors and the same imageSetConfig.yaml used in both tries in different oc-mirror binaries.

imageSet:
apiVersion: [mirror.openshift.io/v1alpha2](http://mirror.openshift.io/v1alpha2)
kind: ImageSetConfiguration
archiveSize: 50
mirror:
  operators:
  - catalog: [registry.redhat.io/redhat/redhat-operator-index:v4.10](http://registry.redhat.io/redhat/redhat-operator-index:v4.10)
    packages:
    - name: advanced-cluster-management
      channels:
      - name: release-2.4
        minVersion: '2.4.9'
        maxVersion: '2.4.9'

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/71714540/207908563-7fd0a871-d02b-470b-9b7a-090c624ab6ac.png">

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/71714540/207908469-e243b35b-994f-41c5-ab94-1bdd4622a4bd.png">

_Originally posted by @Destorntw in https://github.com/openshift/oc-mirror/issues/497#issuecomment-1353319542_

**Comment by ryran** [comment]
I'm just a user, but I ran into a similar issue today and got a lengthy explanation from someone familiar with the project. Here's my distillation of the most important take-away from that:

- **You often won't be able to sync some non-default channel by itself; if it errors out, you need to also include the default channel (at least one version).**

So for ACM, if you want to sync `release-2.4` (at a time like now when the default channel is currently `release-2.6`), you'd need to do something like this:

```yaml
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
    packages:
    - name: advanced-cluster-management
      channels:
      - name: release-2.6
        minVersion: 2.6.0
        maxVersion: 2.6.0
      - name: release-2.4
        minVersion: 2.4.9
        maxVersion: 2.4.9
```

**Comment by ehsjoar** [comment]
Thanks @ryran !
This helps us. At the same time I feel this has to be a bug. If I want to mirror an image in an existing channel, why on earth would I need to also mirror an image from the default channel? Specifically if I don't want/need it.

**Comment by ryran** [comment]
For the record, according to the [4.15 Release notes](https://docs.openshift.com/container-platform/4.15/release_notes/ocp-4-15-release-notes.html#ocp-4-15-openshift-cli-bug-fixes), it looks like this has finally been addressed.

> Previously, to filter operator packages by channel, for example, `mirror.operators.catalog.packages.channels`, you had to specify the default channel for the package, even if you did not intend to use the packages from that channel. Based on this information, the resulting catalog is considered invalid if the imageSetConfig does not contain the default channel for the package.
>
> This update introduces the `defaultChannel` field in the `mirror.operators.catalog.packages` section. You can now select a default channel. This action enables oc-mirror to build a new catalog that defines the selected channel in the `defaultChannel` field as the default for the package. ([OCPBUGS-385](https://issues.redhat.com/browse/OCPBUGS-385))

Digging a little more into that bug, you can see the fix was released with the following versions:

- 4.12.51
- 4.13.34
- 4.14.12
- 4.15.0

Testing it out with the following yaml:

``` yaml
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local: {'path': './operator-images'}
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    packages:
    - name: advanced-cluster-management
      # this was done at a time when the default channel was "release-2.9"
      channels:
      - name: release-2.8
        minVersion: 2.8.5
        maxVersion: 2.8.5
```

As expected, it fails.

``` console
$ ~/oc-mirror-4.14.15 --dry-run -c ~/isc.yml file://operator-images
Logging to .oc-mirror.log
Creating directory: operator-images/oc-mirror-workspace/src/publish
Creating directory: operator-images/oc-mirror-workspace/src/v2
Creating directory: operator-images/oc-mirror-workspace/src/charts
Creating directory: operator-images/oc-mirror-workspace/src/release-signatures
No metadata detected, creating new workspace
The current default channel was not valid, so an attempt was made to automatically assign a new default channel, which has failed.
The failure occurred because none of the remaining channels contain an "olm.channel" priority property, so it was not possible to establish a channel to use as the default channel.

This can be resolved by one of the following changes:
1) assign an "olm.channel" property on the appropriate channels to establish a channel priority
2) modify the default channel manually in the catalog
3) by changing the ImageSetConfiguration to filter channels or packages in such a way that it will include a package version that exists in the current default channel

The rendered catalog is invalid.

Run "oc-mirror list operators --catalog CATALOG-NAME --package PACKAGE-NAME" for more information.

error: error generating diff: the current default channel "release-2.9" for package "advanced-cluster-management" could not be determined... ensure that your ImageSetConfiguration filtering criteria results in a package version that exists in the current default channel or use the 'defaultChannel' field 
```

After adding the new `defaultChannel` setting...

``` patch
--- isc.yml	2024-03-18 18:13:52.718645590 +0000
+++ isc-updated.yml	2024-03-18 18:18:17.382196664 +0000
@@ -7,6 +7,7 @@
   - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
     packages:
     - name: advanced-cluster-management
+      defaultChannel: release-2.8
       channels:
       - name: release-2.8
         minVersion: 2.8.5
```

... It now works!

``` console
$ rm -rf operator-images
$ ~/oc-mirror-4.14.15 --dry-run -c ~/isc-updated.yml file://operator-images
Creating directory: operator-images/oc-mirror-workspace/src/publish
Creating directory: operator-images/oc-mirror-workspace/src/v2
Creating directory: operator-images/oc-mirror-workspace/src/charts
Creating directory: operator-images/oc-mirror-workspace/src/release-signatures
No metadata detected, creating new workspace
wrote mirroring manifests to operator-images/oc-mirror-workspace/operators.1710785910/manifests-redhat-operator-index
...
  stats: shared=24 unique=378 size=7.359GiB ratio=0.85
...
info: Planning completed in 6.56s
info: Dry run complete
```
