### ISSUE TITLE
[RFE] Generate an install-config.yaml snippet to be used during initial install.

### ISSUE THREAD

**Issue by nnachefski** [openshift/oc-mirror#539]
oc mirror currently writes catalogSource and imageContentSourcePolicy manifests to the 'results' folder.  This does nothing for me to use during actual install time.  The install-config.yaml doesnt take the imageContentSourcePolicy file as is, however, the content is much the same.  For instance, this is what is written:

```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: release-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - repo.lab.arrowglance.io:5000/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - repo.lab.arrowglance.io:5000/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
```

But, in order to get Openshift to use these sources during install time, i need something more like this in the install-config.yaml:

```
imageContentSources:
  - mirrors:
    - repo.lab.arrowglance.io:5000/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - repo.lab.arrowglance.io:5000/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
```

Pretty much the same thing but in a slightly different format.  It would be nice if oc-mirror could write me a snippet to use in the install-config.yaml so that all i had to do is:
```
cat installConfig-ImageContentSource-snippet.yaml >> install-config.yaml
```

-Nick
