### ISSUE TITLE
Can't run oc-mirror on low spec VM

### ISSUE THREAD

**Issue by ahussey-redhat** [openshift/oc-mirror#545]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-76-g159c539", GitCommit:"159c5394", GitTreeState:"clean", BuildDate:"2023-01-11T01:33:11Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

When attempting to list, or mirror any content on a machine that has limited memory (4GB) and limited SWAP (2GB) I receive the following error:
```bash
error: render reference "registry.redhat.io/redhat/redhat-operator-index:v4.10": write /tmp/render-unpack-1874233107/usr/lib64/python3.6/__pycache__/tracemalloc.cpython-36.opt-1.pyc: no space left on device
```

# What did you expect to happen?

I expect the command to run successfully.

# How to reproduce it (as minimally and precisely as possible)?

1. create a VM with 2GB of SWAP, 4GB of memory and 60GB+ of storage.
2. clone the `oc-mirror` repo
3. install all deps, then `make build`
4. use the resulting binary to run the following commands
    - `oc-mirror list operators --catalog registry.redhat.io/redhat/redhat-operator-index:v4.10 --package devspaces`
    - `oc mirror -c ./operators.yml --dry-run file:///var/tmp/mirror`
        - where `operators.yml` contains:
        ```yaml
        ---
        apiVersion: mirror.openshift.io/v1alpha2
        kind: ImageSetConfiguration
        storageConfig:
          local:
            path: /var/tmp/mirror
        mirror:
          operators:
            - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
              packages:
                - name: devspaces
                  channels:
                    - name: stable
                      minVersion: '3.3.0'
        ```
After running each of the above commands, I received the same error.
