### ISSUE TITLE
Using oc-mirror with headsonly fails digest errors referring to article #6138332

### ISSUE THREAD

**Issue by momoah** [openshift/oc-mirror#571]
# Version

```console
# oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.12.0-202302280915.p0.g3d51740.assembly.stream-3d51740", GitCommit:"3d517407dcbc46ededd7323c7e8f6d6a45efc649", GitTreeState:"clean", BuildDate:"2023-03-01T00:20:53Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}

```

# What happened?

When mirroring content from registry.redhat.io/redhat/redhat-operator-index:v4.10 with the following imageset-config.yaml (which is based on https://github.com/openshift/oc-mirror/blob/main/docs/examples/imageset-config-catalog-headsonly.yaml):

```
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: myregistry.mydomain:5000/redhat-operators
    skipTLS: false
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
```
then run:

```
# oc mirror --config=./imageset-config.yaml docker://myregistry.mydomain:5000/redhat-operators
error: unable to retrieve source image registry.redhat.io/openshift-service-mesh/grafana-rhel8 manifest sha256:070d8ffd0a11158a8a5769ef9854109e70d911bb9adcce35449db33037df99d0: unsupported: Not Found, or unsupported. V2 schema 1 manifest digest are no longer supported for image pulls. Use the equivalent schema 2 manifest digest instead. For more information see https://access.redhat.com/articles/6138332
```
Attaching my  `.oc-mirror.log`.

# What did you expect to happen?

For it to mirror the operator containers to my local registry. It works when a few containers are chosen (such as the serverless-operator)

# How to reproduce it (as minimally and precisely as possible)?

```console

oc mirror --config=./imageset-config.yaml docker://myregistry.mydomain:5000/redhat-operators

error: unable to retrieve source image registry.redhat.io/openshift-service-mesh/grafana-rhel8 manifest sha256:070d8ffd0a11158a8a5769ef9854109e70d911bb9adcce35449db33037df99d0: unsupported: Not Found, or unsupported. V2 schema 1 manifest digest are no longer supported for image pulls. Use the equivalent schema 2 manifest digest instead. For more information see https://access.redhat.com/articles/6138332

```

Full log in log-file.

And then the command exits.

# Anything else we need to know?

I haven't tested this for 4.11 and 4.12

# References
1. https://docs.openshift.com/container-platform/4.12/installing/disconnected_install/installing-mirroring-disconnected.html#installing-mirroring-disconnected
