### ISSUE TITLE
oc-mirror doesn't pull latest version in channel after removing maxversion/minversion

### ISSUE THREAD

**Issue by ehsjoar** [openshift/oc-mirror#626]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.13.0-202301161406.p0.gcf167e8.assembly.stream-cf167e8", GitCommit:"cf167e8425339c15b4b9a80071a8f6ae024ffdde", GitTreeState:"clean", BuildDate:"2023-01-16T14:27:43Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

running oc-mirror with the following pulls down ptp-operator 4.12.0-202303021731
```
oc-mirror --config=./imageset-config.yaml docker://registry.ocp4.ocp412.com:5000/ocp412
```
And the image set config
```
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: /home/jonas/registry/data/
mirror:
  platform:
    channels:
    - name: stable-4.12
      minversion: 4.12.4
      maxversion: 4.12.4
      type: ocp
    graph: true
 operators:
   - name: ptp-operator
     channels:
     - name: stable
       minversion: 4.12.0-202303021731
       maxversion: 4.12.0-202303021731
...
```
Then when removing minversion / maxversion  and running it again (same command syntax) and received "No new images detected, process stopping".

# What did you expect to happen?
I would expect oc-mirror to pull down the latest version in the stable channel, which currently is 4.12.0-202304211142. 
It feels to me like a bug but I am not sure what is expected to happen when you change your image set config like this.

# How to reproduce it (as minimally and precisely as possible)?

This is pretty clear I think from above

# Anything else we need to know?

Nope
