### ISSUE TITLE
oc mirror from imagesets failed to build catalog image

### ISSUE THREAD

**Issue by theodor2311** [openshift/oc-mirror#629]
# Version

```console
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.12.0-202304070941.p0.g7635353.assembly.stream-7635353", GitCommit:"7635353ed12fdcb725855b1d4165cfec8dc10e16", GitTreeState:"clean", BuildDate:"2023-04-07T10:11:09Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?
oc mirror from imagesets failed to build catalog image.

```
rebuilding catalog images
Rendering catalog image "test.local:8443/redhat/redhat-operator-index:v4.12" with file-based catalog
"Using existing OCI layout to oc-mirror-workspace/images.3253033354/catalogs/registry.redhat.io/redhat/redhat-operator-index/v4.12/layout"
error: error rebuilding catalog images from file-based catalogs: error creating OCI layout: stat oc-mirror-workspace/images.3253033354/catalogs/registry.redhat.io/redhat/redhat-operator-index/v4.12/layout/index.json: no such file or directory
```

# What did you expect to happen?

The oc mirror from imagesets should run without error.

# How to reproduce it (as minimally and precisely as possible)?
Using the following command on the same machine with my testing imageset-config.yaml configuration will produce the error every time.
```bash
oc mirror --config=./imageset-config.yaml file://mirror
oc mirror --from=mirror docker://test.local:8443 --dest-skip-tls -v=9
```
**imageset-config.yaml**
```yaml
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 1
storageConfig:
  local:
    path: metadata
mirror:
  platform:
    architectures:
      - amd64
    channels:
    - name: eus-4.12
      minVersion: 4.12.13
      maxVersion: 4.12.13
    - name: stable-4.12
      minVersion: 4.12.13
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.12
    packages:
    - name: 3scale-operator
      channels:
      - name: threescale-2.13
    - name: local-storage-operator
      channels:
      - name: stable
    - name: cluster-logging
      channels:
      - name: stable
    - name: elasticsearch-operator
      channels:
      - name: stable
```

# Anything else we need to know?
Using the same configuration with the partially disconnected approach is working fine for me.
```bash
oc mirror --config=./imageset-config.yaml docker://test.local:8443 --dest-skip-tls # Working fine
```
