### ISSUE TITLE
oc-mirror v2 itms missing

### ISSUE THREAD

**Issue by abulfat-masimov** [openshift/oc-mirror#803]
# Version

```console
$ ./oc-mirror --v2 --version
--v2 flag identified, flow redirected to the oc-mirror v2 version. PLEASE DO NOT USE that. V2 is still under development and it is not ready to be used. 
oc-mirror version v2.0.0-dev-01
```
oc-mirror was sourced from https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview/4.16.0-ec.2/oc-mirror.tar.gz

# What happened?

oc-mirror only generates idms and I could not locate --generate-itms parameter.

# What did you expect to happen?

I'd expect it to generate both itms and idms files.

# How to reproduce it (as minimally and precisely as possible)?

imageset-config-additional-images.yaml:
```
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: art.sample.com/mirrorv2/mirror-metadata/additional-images
mirror:
  additionalImages:
  - name: "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0"
  - name: registry.twistlock.com/twistlock/defender:defender_31_03_103
  - name: docker.io/otel/opentelemetry-collector-contrib:latest
  - name: quay.io/prometheus/prometheus:v2.46.0
  - name: quay.io/openshift-community-operators/cockroachdb@sha256:a5d4f4467250074216eb1ba1c36e06a3ab797d81c431427fc2aca97ecaf4e9d8 
```

```console
$ ./oc-mirror --v2 -c imageset-config-additional-images.yaml file:///downloads/mirrordir1
$ ./oc-mirror --v2 -c imageset-config-additional-images.yaml --from file:///downloads/mirrordir1/ docker://art.sample.com/mirrorv2
```

# Anything else we need to know?

I'd appreciate if you tell when v2 will be GA and if it will be supported on RHEL8.
Thank you in advance!
