### ISSUE TITLE
possible to replace `oc adm release mirror` for imageContentSources generation and image download?

### ISSUE THREAD

**Issue by brightzheng100** [openshift/oc-mirror#873]
Currently, as per the doc, there is a need to generate the `imageContentSources` with command like:

```sh
$ oc adm release mirror \
    --registry-config=${LOCAL_SECRET_JSON} \
    --from=quay.io/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE}-${ARCHITECTURE} \
    --to=${LOCAL_REGISTRY}/${LOCAL_REPOSITORY} \
    --to-release-image=${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}:${OCP_RELEASE}-${ARCHITECTURE} \
    --dry-run
```

So that we can have something like:
```yaml
imageContentSources:
- mirrors:
  - registry.ocp4.local:8443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.ocp4.local:8443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
```

And then download the OpenShift cluster images with another command:

```sh
$ oc adm release mirror \
    --registry-config=${LOCAL_SECRET_JSON} \
    --to-dir=${REMOVABLE_MEDIA_PATH} \
    quay.io/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE}-${ARCHITECTURE}
```

So question: Is it possible to use `oc-mirror` to
1.  generate such `imageContentSources` YAML section for `install-config.yaml`?
2. download OpenShift cluster images without the need of `oc adm release mirror`?

Look forward to your advice. Thank you!
